### ISSUE TITLE
Complete PASch Code

### ISSUE THREAD

**Issue by liwen-tj** [disel-espol/olscheduler#8]
I know this is an extension to OpenLambda. I alse read source code of OpenLambda. I find there is only one worker(process) in OpenLambda. You cannot new a worker. But in your ol-scheduler, you have many workers in config.json. I donot understand how you combined your code with Openlambda.

By the way, I also read your paper PASch. I don't find PASch branch in https://github.com/open-lambda/open-lambda. Will you please give me the complete source code of PASch. I am very curious about how you did your experiments in PASch. I really want to read it! Many thanks!

**Comment by cristina-abad** [comment]
To get olscheduler to work, you first need a workin OpenLambda installation. OpenLambda does support multiple workers, running in different VMs. They don't have an olscheduler branch because we are two independent projects. We did ask them a couple of questions when trying to get OpenLambda to work and they were helpful, so you may try that. Once you have an OpenLambda setup running, including Pipbench, you can try olscheduler. We will be glad to help you with issues that may arise then. However, we cannot help with issues related to getting OpenLambda up and running.
